/* Generated by generate_ghidra_types.py; do not edit.
   generator_version 1
   derived from ../public_header_hashes.json and ../../novodex-foundation/dumps/immutable_public_hashes.json,
   whose sha256 physics_type_inputs.json pins and this generator verifies before parsing.
   C++ spellings are replaced by layout-identical C ones: __int64 -> long long, bool -> unsigned char, references -> pointers.
*/

typedef struct Nx12Real Nx12Real;
typedef struct Nx12Real_S Nx12Real_S;
typedef struct Nx16Real Nx16Real;
typedef struct Nx16Real_S Nx16Real_S;
typedef struct Nx9Real Nx9Real;
typedef struct Nx9Real_S Nx9Real_S;
typedef struct NxActor NxActor;
typedef struct NxActorDesc NxActorDesc;
typedef struct NxActorDescBase NxActorDescBase;
typedef struct NxAllocateable NxAllocateable;
typedef struct NxAllocatorDefault NxAllocatorDefault;
typedef struct NxBitField NxBitField;
typedef struct NxBitField_FlagRef NxBitField_FlagRef;
typedef struct NxBodyDesc NxBodyDesc;
typedef struct NxBounds3 NxBounds3;
typedef struct NxBox NxBox;
typedef struct NxBoxShape NxBoxShape;
typedef struct NxBoxShapeDesc NxBoxShapeDesc;
typedef struct NxCapsule NxCapsule;
typedef struct NxCapsuleShape NxCapsuleShape;
typedef struct NxCapsuleShapeDesc NxCapsuleShapeDesc;
typedef struct NxContactPair NxContactPair;
typedef struct NxContactStreamIterator NxContactStreamIterator;
typedef struct NxCylindricalJoint NxCylindricalJoint;
typedef struct NxCylindricalJointDesc NxCylindricalJointDesc;
typedef struct NxD6Joint NxD6Joint;
typedef struct NxD6JointDesc NxD6JointDesc;
typedef struct NxDebugLine NxDebugLine;
typedef struct NxDebugPoint NxDebugPoint;
typedef struct NxDebugRenderable NxDebugRenderable;
typedef struct NxDebugTriangle NxDebugTriangle;
typedef struct NxDistanceJoint NxDistanceJoint;
typedef struct NxDistanceJointDesc NxDistanceJointDesc;
typedef struct NxEffector NxEffector;
typedef struct NxException NxException;
typedef struct NxFixedJoint NxFixedJoint;
typedef struct NxFixedJointDesc NxFixedJointDesc;
typedef struct NxFluid NxFluid;
typedef struct NxFluidContactPair NxFluidContactPair;
typedef struct NxFluidDesc NxFluidDesc;
typedef struct NxFluidEmitter NxFluidEmitter;
typedef struct NxFluidEmitterDesc NxFluidEmitterDesc;
typedef struct NxFoundationSDK NxFoundationSDK;
typedef struct NxImplicitMesh NxImplicitMesh;
typedef struct NxImplicitMeshDesc NxImplicitMeshDesc;
typedef struct NxIntegrals NxIntegrals;
typedef struct NxJoint NxJoint;
typedef struct NxJointDesc NxJointDesc;
typedef struct NxJointDriveDesc NxJointDriveDesc;
typedef struct NxJointLimitDesc NxJointLimitDesc;
typedef struct NxJointLimitPairDesc NxJointLimitPairDesc;
typedef struct NxMat33 NxMat33;
typedef struct NxMat34 NxMat34;
typedef struct NxMaterial NxMaterial;
typedef struct NxMath NxMath;
typedef struct NxMeshData NxMeshData;
typedef struct NxMotorDesc NxMotorDesc;
typedef struct NxPMap NxPMap;
typedef struct NxPairFlag NxPairFlag;
typedef struct NxParticleData NxParticleData;
typedef struct NxPerformanceInspector NxPerformanceInspector;
typedef struct NxPhysicsSDK NxPhysicsSDK;
typedef struct NxPlane NxPlane;
typedef struct NxPlaneShape NxPlaneShape;
typedef struct NxPlaneShapeDesc NxPlaneShapeDesc;
typedef struct NxPointInPlaneJoint NxPointInPlaneJoint;
typedef struct NxPointInPlaneJointDesc NxPointInPlaneJointDesc;
typedef struct NxPointOnLineJoint NxPointOnLineJoint;
typedef struct NxPointOnLineJointDesc NxPointOnLineJointDesc;
typedef struct NxPrismaticJoint NxPrismaticJoint;
typedef struct NxPrismaticJointDesc NxPrismaticJointDesc;
typedef struct NxProfiler NxProfiler;
typedef struct NxProfiler_History_Scalar NxProfiler_History_Scalar;
typedef struct NxProfiler_Profile_Tracker_Data_Record NxProfiler_Profile_Tracker_Data_Record;
typedef struct NxProfiler_SetCurrentZone NxProfiler_SetCurrentZone;
typedef struct NxProfilingZone NxProfilingZone;
typedef struct NxPulleyJoint NxPulleyJoint;
typedef struct NxPulleyJointDesc NxPulleyJointDesc;
typedef struct NxQuat NxQuat;
typedef struct NxRay NxRay;
typedef struct NxRaycastHit NxRaycastHit;
typedef struct NxRevoluteJoint NxRevoluteJoint;
typedef struct NxRevoluteJointDesc NxRevoluteJointDesc;
typedef struct NxScene NxScene;
typedef struct NxSceneDesc NxSceneDesc;
typedef struct NxSceneLimits NxSceneLimits;
typedef struct NxSceneStats NxSceneStats;
typedef struct NxSegment NxSegment;
typedef struct NxSetCurrentZone NxSetCurrentZone;
typedef struct NxShape NxShape;
typedef struct NxShapeDesc NxShapeDesc;
typedef struct NxSimpleTriangleMesh NxSimpleTriangleMesh;
typedef struct NxSphere NxSphere;
typedef struct NxSphereShape NxSphereShape;
typedef struct NxSphereShapeDesc NxSphereShapeDesc;
typedef struct NxSphericalJoint NxSphericalJoint;
typedef struct NxSphericalJointDesc NxSphericalJointDesc;
typedef struct NxSpringAndDamperEffector NxSpringAndDamperEffector;
typedef struct NxSpringAndDamperEffectorDesc NxSpringAndDamperEffectorDesc;
typedef struct NxSpringDesc NxSpringDesc;
typedef struct NxStream NxStream;
typedef struct NxTriangle NxTriangle;
typedef struct NxTriangle32 NxTriangle32;
typedef struct NxTriangleMesh NxTriangleMesh;
typedef struct NxTriangleMeshDesc NxTriangleMeshDesc;
typedef struct NxTriangleMeshShape NxTriangleMeshShape;
typedef struct NxTriangleMeshShapeDesc NxTriangleMeshShapeDesc;
typedef struct NxUserAllocator NxUserAllocator;
typedef struct NxUserAllocatorAccess NxUserAllocatorAccess;
typedef struct NxUserAllocatorDefault NxUserAllocatorDefault;
typedef struct NxUserContactReport NxUserContactReport;
typedef struct NxUserDebugRenderer NxUserDebugRenderer;
typedef struct NxUserFluidContactReport NxUserFluidContactReport;
typedef struct NxUserNotify NxUserNotify;
typedef struct NxUserOutputStream NxUserOutputStream;
typedef struct NxUserRaycastReport NxUserRaycastReport;
typedef struct NxUserTriggerReport NxUserTriggerReport;
typedef struct NxVec3 NxVec3;

/* forced declaration: NxArray<NxFluidEmitterDesc>
   Class template instantiation; R6 does not instantiate templates. The three pointer
   fields are the 'Iterator first, last, memEnd;' declared at
   Foundation/include/NxArray.h:410, with Iterator = ElemType* per NxArray.h:26. The
   trailing field stands for the 'AllocType allocator;' at NxArray.h:412, whose type
   NxAllocatorDefault declares only member functions. ASSUMPTION NOT YET VERIFIED AGAINST
   THE BINARY: this assumes MSVC empty-base optimization for the NxAllocateable base (0
   bytes) and a 1-byte empty-class member padded to the struct's 4-byte alignment, giving
   16 bytes total. Task 5 must confirm the size against the oracle before any
   reconstruction relies on it.
*/
typedef struct NxArray_NxFluidEmitterDesc {
    NxFluidEmitterDesc *first;
    NxFluidEmitterDesc *last;
    NxFluidEmitterDesc *memEnd;
    unsigned char allocator;
} NxArray_NxFluidEmitterDesc;

/* forced declaration: NxArray<NxShapeDesc*>
   Class template instantiation; R6 does not instantiate templates. The three pointer
   fields are the 'Iterator first, last, memEnd;' declared at
   Foundation/include/NxArray.h:410, with Iterator = ElemType* per NxArray.h:26. The
   trailing field stands for the 'AllocType allocator;' at NxArray.h:412, whose type
   NxAllocatorDefault declares only member functions. ASSUMPTION NOT YET VERIFIED AGAINST
   THE BINARY: this assumes MSVC empty-base optimization for the NxAllocateable base (0
   bytes) and a 1-byte empty-class member padded to the struct's 4-byte alignment, giving
   16 bytes total. Task 5 must confirm the size against the oracle before any
   reconstruction relies on it.
*/
typedef struct NxArray_NxShapeDesc_ptr {
    NxShapeDesc **first;
    NxShapeDesc **last;
    NxShapeDesc **memEnd;
    unsigned char allocator;
} NxArray_NxShapeDesc_ptr;

enum NxErrorCode {
    NXE_NO_ERROR = 0,
    NXE_INVALID_PARAMETER = 1,
    NXE_INVALID_OPERATION = 2,
    NXE_OUT_OF_MEMORY = 3,
    NXE_INTERNAL_ERROR = 4,
    NXE_ASSERTION = 107,
    NXE_DB_INFO = 205,
    NXE_DB_WARNING = 206,
    NXE_DB_PRINT = 208,
    NxErrorCode__nx_force_32bit = 2147483647
};

struct NxAllocateable {
    char __empty;
};

struct NxAllocatorDefault {
    char __empty;
};

enum NxDebugColor {
    NX_ARGB_BLACK = 4278190080,
    NX_ARGB_RED = 4294901760,
    NX_ARGB_GREEN = 4278255360,
    NX_ARGB_BLUE = 4278190335,
    NX_ARGB_YELLOW = 4294967040,
    NX_ARGB_MAGENTA = 4294902015,
    NX_ARGB_CYAN = 4278255615,
    NX_ARGB_WHITE = 4294967295
};

struct NxDebugRenderable {
    void **__vftable;
};

struct NxException {
    void **__vftable;
};

struct NxFoundationSDK {
    void **__vftable;
};

enum NxMatrixType {
    NX_ZERO_MATRIX = 0,
    NX_IDENTITY_MATRIX = 1,
    NxMatrixType__nx_force_32bit = 2147483647
};

struct NxMath {
    char __empty;
};

struct NxProfilingZone {
    void **__vftable;
};

struct NxSetCurrentZone {
    NxProfilingZone *zone;
};

enum NxDisplayMode {
    NX_SELF_TIME = 0,
    NX_HIERARCHICAL_TIME = 1,
    NX_SELF_STDEV = 2,
    NX_HIERARCHICAL_STDEV = 3,
    NxDisplayMode__nx_force_32bit = 2147483647
};

struct NxProfiler {
    char __empty;
};

/* excluded type: NxProfiler_DefineZone
   UNDERIVABLE UNDER THE TARGET ABI - not merely unverified, and not closed by verifying
   it. Foundation/include/NxProfiler.h:76 declares 'class DefineZone : public
   NxAllocateable, public NxProfilingZone', the only multiple-inheritance site in either
   pinned tree. NxAllocateable declares only operator new/delete, so it is empty and
   non-polymorphic; NxProfilingZone declares three pure virtuals, so it is polymorphic
   and forces a vftable slot. Deriving the layout would require assuming the empty base
   is elided, and MSVC's default Win32 ABI does not reliably apply empty-base
   optimization when a class has multiple bases - that is precisely why
   __declspec(empty_bases) was later added to the compiler. For the 2003-era MSVC that
   built this DLL, 'EBO applies' is a coin flip, not a conservative default, and guessing
   wrong would place the vftable slot and every field after it at the wrong offset while
   decompiling confidently. R4 therefore withholds the type rather than emitting a layout
   it cannot derive. Nothing in the Physics tree reaches it: NxPerformanceInspector is
   declared in Physics/include/NxSceneStats.h, not here, and all three of NxProfiler's
   DefineZone members (NxProfiler.h:153, :169, :188) are static. The generator
   hard-errors if this type ever becomes reachable.
*/

struct NxProfiler_SetCurrentZone {
    char __empty;
};

struct NxProfiler_History_Scalar {
    double values[3];
    double variances[3];
};

struct NxProfiler_Profile_Tracker_Data_Record {
    int index;
    NxProfiler_History_Scalar self_time;
    NxProfiler_History_Scalar hierarchical_time;
    NxProfiler_History_Scalar entry_count;
    double displayed_quantity;
};

enum NxMeshFlags {
    NX_MF_FLIPNORMALS = 1,
    NX_MF_16_BIT_INDICES = 2,
    NX_MF_CONVEX = 4,
    NX_MF_COMPUTE_CONVEX = 8,
    NxMeshFlags__nx_force_32bit = 2147483647
};

typedef long long NxI64;

typedef signed int NxI32;

typedef signed short NxI16;

typedef signed char NxI8;

typedef unsigned long long NxU64;

typedef unsigned int NxU32;

struct NxBitField {
    NxU32 bitField;
};

struct NxBitField_FlagRef {
    NxBitField *bitField;
    NxU32 bitIndex;
};

typedef NxBitField NxBitField32;

struct NxSimpleTriangleMesh {
    NxU32 numVertices;
    NxU32 numTriangles;
    NxU32 pointStrideBytes;
    NxU32 triangleStrideBytes;
    void *points;
    void *triangles;
    NxU32 flags;
};

typedef unsigned short NxU16;

typedef unsigned char NxU8;

typedef float NxF32;

typedef double NxF64;

typedef int NX_BOOL;

enum NxBSphereMethod {
    NX_BS_NONE = 0,
    NX_BS_GEMS = 1,
    NX_BS_MINIBALL = 2,
    NX_BS_FORCE_DWORD = 2147483647
};

struct NxStream {
    void **__vftable;
};

enum NxMemoryType {
    NX_MEMORY_PERSISTENT = 0,
    NX_MEMORY_TEMP = 1,
    NxMemoryType__nx_force_32bit = 2147483647
};

struct NxUserAllocator {
    void **__vftable;
};

struct NxUserAllocatorAccess {
    char __empty;
};

struct NxUserAllocatorDefault {
    NxUserAllocator __base_NxUserAllocator;
};

struct NxUserDebugRenderer {
    void **__vftable;
};

enum NxAssertResponse {
    NX_AR_CONTINUE = 0,
    NX_AR_IGNORE = 1,
    NX_AR_BREAKPOINT = 2,
    NxAssertResponse__nx_force_32bit = 2147483647
};

struct NxUserOutputStream {
    void **__vftable;
};

enum NxAxisType {
    NX_AXIS_PLUS_X = 0,
    NX_AXIS_MINUS_X = 1,
    NX_AXIS_PLUS_Y = 2,
    NX_AXIS_MINUS_Y = 3,
    NX_AXIS_PLUS_Z = 4,
    NX_AXIS_MINUS_Z = 5,
    NX_AXIS_ARBITRARY = 6,
    NxAxisType__nx_force_32bit = 2147483647
};

typedef NxF32 NxReal;

struct Nx12Real_S {
    NxReal _11;
    NxReal _12;
    NxReal _13;
    NxReal _14;
    NxReal _21;
    NxReal _22;
    NxReal _23;
    NxReal _24;
    NxReal _31;
    NxReal _32;
    NxReal _33;
    NxReal _34;
};

struct Nx12Real {
    union {
        Nx12Real_S s;
        NxReal m[3][4];
    } __anon_0;
};

struct Nx16Real_S {
    NxReal _11;
    NxReal _12;
    NxReal _13;
    NxReal _14;
    NxReal _21;
    NxReal _22;
    NxReal _23;
    NxReal _24;
    NxReal _31;
    NxReal _32;
    NxReal _33;
    NxReal _34;
    NxReal _41;
    NxReal _42;
    NxReal _43;
    NxReal _44;
};

struct Nx16Real {
    union {
        Nx16Real_S s;
        NxReal m[4][4];
    } __anon_0;
};

struct Nx9Real_S {
    NxReal _11;
    NxReal _12;
    NxReal _13;
    NxReal _21;
    NxReal _22;
    NxReal _23;
    NxReal _31;
    NxReal _32;
    NxReal _33;
};

struct Nx9Real {
    union {
        Nx9Real_S s;
        NxReal m[3][3];
    } __anon_0;
};

typedef Nx9Real Mat33DataType;

struct NxMat33 {
    Mat33DataType data;
};

struct NxQuat {
    NxReal x;
    NxReal y;
    NxReal z;
    NxReal w;
};

struct NxVec3 {
    NxReal x;
    NxReal y;
    NxReal z;
};

struct NxBounds3 {
    NxVec3 min;
    NxVec3 max;
};

struct NxBox {
    NxVec3 center;
    NxVec3 extents;
    NxMat33 rot;
};

struct NxDebugPoint {
    NxVec3 p;
    NxU32 color;
};

struct NxDebugLine {
    NxVec3 p0;
    NxVec3 p1;
    NxU32 color;
};

struct NxDebugTriangle {
    NxVec3 p0;
    NxVec3 p1;
    NxVec3 p2;
    NxU32 color;
};

struct NxMat34 {
    NxMat33 M;
    NxVec3 t;
};

struct NxPlane {
    NxVec3 normal;
    NxF32 d;
};

struct NxRay {
    NxVec3 orig;
    NxVec3 dir;
};

struct NxSegment {
    NxVec3 p0;
    NxVec3 p1;
};

struct NxCapsule {
    NxSegment __base_NxSegment;
    NxF32 radius;
};

typedef NxVec3 NxPoint;

struct NxSphere {
    NxVec3 center;
    NxF32 radius;
};

struct NxIntegrals {
    NxVec3 COM;
    NxF64 mass;
    NxF64 inertiaTensor[3][3];
    NxF64 COMInertiaTensor[3][3];
};

enum NxForceMode {
    NX_FORCE = 0,
    NX_IMPULSE = 1,
    NX_VELOCITY_CHANGE = 2,
    NX_SMOOTH_IMPULSE = 3,
    NX_SMOOTH_VELOCITY_CHANGE = 4,
    NxForceMode__nx_force_32bit = 2147483647
};

struct NxActor {
    void **__vftable;
    void *userData;
};

enum NxActorFlag {
    NX_AF_DISABLE_COLLISION = 1,
    NX_AF_DISABLE_RESPONSE = 2,
    NX_AF_FLUID_DISABLE_COLLISION = 4,
    NX_AF_FLUID_ACTOR_REACTION = 8,
    NxActorFlag__nx_force_32bit = 2147483647
};

enum ActorDescType {
    NX_ADT_SHAPELESS = 0,
    NX_ADT_DEFAULT = 1,
    NX_ADT_ALLOCATOR = 2,
    NX_ADT_LIST = 3,
    NX_ADT_POINTER = 4,
    ActorDescType__nx_force_32bit = 2147483647
};

enum NxBodyFlag {
    NX_BF_DISABLE_GRAVITY = 1,
    NX_BF_FROZEN_POS_X = 2,
    NX_BF_FROZEN_POS_Y = 4,
    NX_BF_FROZEN_POS_Z = 8,
    NX_BF_FROZEN_ROT_X = 16,
    NX_BF_FROZEN_ROT_Y = 32,
    NX_BF_FROZEN_ROT_Z = 64,
    NX_BF_FROZEN_POS = 14,
    NX_BF_FROZEN_ROT = 112,
    NX_BF_FROZEN = 126,
    NX_BF_KINEMATIC = 128,
    NX_BF_VISUALIZATION = 256,
    NxBodyFlag__nx_force_32bit = 2147483647
};

struct NxBodyDesc {
    NxMat34 massLocalPose;
    NxVec3 massSpaceInertia;
    NxReal mass;
    NxVec3 linearVelocity;
    NxVec3 angularVelocity;
    NxReal wakeUpCounter;
    NxReal linearDamping;
    NxReal angularDamping;
    NxReal maxAngularVelocity;
    NxU32 flags;
    NxReal sleepLinearVelocity;
    NxReal sleepAngularVelocity;
    NxU32 solverIterationCount;
};

enum NxCapsuleShapeFlag {
    NX_SWEPT_SHAPE = 1,
    NxCapsuleShapeFlag__nx_force_32bit = 2147483647
};

typedef NxU32 *NxContactStream;

typedef NxU32 *NxConstContactStream;

enum NxShapePairStreamFlags {
    NX_SF_HAS_MATS_PER_POINT = 1,
    NX_SF_IS_INVALID = 2,
    NX_SF_HAS_FEATURES_PER_POINT = 4,
    NxShapePairStreamFlags__nx_force_32bit = 2147483647
};

struct NxContactStreamIterator {
    NxU32 numPairs;
    NxShape *shapes[2];
    NxU16 shapeFlags;
    NxU16 numPatches;
    NxVec3 *patchNormal;
    NxU32 numPoints;
    NxVec3 *point;
    NxReal separation;
    NxU32 featureIndex0;
    NxU32 featureIndex1;
    NxU32 extData;
    NxU32 numPairsRemaining;
    NxU32 numPatchesRemaining;
    NxU32 numPointsRemaining;
    NxConstContactStream stream;
};

enum NxD6JointDriveType {
    NX_D6JOINT_DRIVE_POSITION = 1,
    NX_D6JOINT_DRIVE_VELOCITY = 2,
    NX_D6JOINT_DRIVE_SLERP = 4,
    NxD6JointDriveType__nx_force_32bit = 2147483647
};

enum NxD6JointMotion {
    NX_D6JOINT_MOTION_LOCKED = 0,
    NX_D6JOINT_MOTION_LIMITED = 1,
    NX_D6JOINT_MOTION_FREE = 2,
    NxD6JointMotion__nx_force_32bit = 2147483647
};

struct NxJointDriveDesc {
    NxBitField32 driveType;
    NxReal spring;
    NxReal damping;
    NxReal forceLimit;
};

enum NxDistanceJointFlag {
    NX_DJF_MAX_DISTANCE_ENABLED = 1,
    NX_DJF_MIN_DISTANCE_ENABLED = 2,
    NX_DJF_SPRING_ENABLED = 4,
    NxDistanceJointFlag__nx_force_32bit = 2147483647
};

struct NxEffector {
    void **__vftable;
    void *userData;
};

enum NxSepAxis {
    NX_SEP_AXIS_OVERLAP = 0,
    NX_SEP_AXIS_A0 = 1,
    NX_SEP_AXIS_A1 = 2,
    NX_SEP_AXIS_A2 = 3,
    NX_SEP_AXIS_B0 = 4,
    NX_SEP_AXIS_B1 = 5,
    NX_SEP_AXIS_B2 = 6,
    NX_SEP_AXIS_A0_CROSS_B0 = 7,
    NX_SEP_AXIS_A0_CROSS_B1 = 8,
    NX_SEP_AXIS_A0_CROSS_B2 = 9,
    NX_SEP_AXIS_A1_CROSS_B0 = 10,
    NX_SEP_AXIS_A1_CROSS_B1 = 11,
    NX_SEP_AXIS_A1_CROSS_B2 = 12,
    NX_SEP_AXIS_A2_CROSS_B0 = 13,
    NX_SEP_AXIS_A2_CROSS_B1 = 14,
    NX_SEP_AXIS_A2_CROSS_B2 = 15,
    NX_SEP_AXIS_FORCE_DWORD = 2147483647
};

enum NxJointType {
    NX_JOINT_PRISMATIC = 0,
    NX_JOINT_REVOLUTE = 1,
    NX_JOINT_CYLINDRICAL = 2,
    NX_JOINT_SPHERICAL = 3,
    NX_JOINT_POINT_ON_LINE = 4,
    NX_JOINT_POINT_IN_PLANE = 5,
    NX_JOINT_DISTANCE = 6,
    NX_JOINT_PULLEY = 7,
    NX_JOINT_FIXED = 8,
    NX_JOINT_D6 = 9,
    NX_JOINT_COUNT = 10,
    NX_JOINT_FORCE_DWORD = 2147483647
};

enum NxJointState {
    NX_JS_UNBOUND = 0,
    NX_JS_SIMULATING = 1,
    NX_JS_BROKEN = 2,
    NxJointState__nx_force_32bit = 2147483647
};

struct NxJoint {
    void **__vftable;
    void *userData;
    void *appData;
};

struct NxCylindricalJoint {
    NxJoint __base_NxJoint;
};

struct NxD6Joint {
    NxJoint __base_NxJoint;
};

struct NxDistanceJoint {
    NxJoint __base_NxJoint;
};

struct NxFixedJoint {
    NxJoint __base_NxJoint;
};

enum NxJointFlag {
    NX_JF_COLLISION_ENABLED = 1,
    NX_JF_VISUALIZATION = 2,
    NxJointFlag__nx_force_32bit = 2147483647
};

enum NxJointProjectionMode {
    NX_JPM_NONE = 0,
    NX_JPM_POINT_MINDIST = 1,
    NxJointProjectionMode__nx_force_32bit = 2147483647
};

struct NxJointDesc {
    void **__vftable;
    NxJointType type;
    NxActor *actor[2];
    NxVec3 localNormal[2];
    NxVec3 localAxis[2];
    NxVec3 localAnchor[2];
    NxReal maxForce;
    NxReal maxTorque;
    void *userData;
    char *name;
    NxU32 jointFlags;
};

struct NxCylindricalJointDesc {
    NxJointDesc __base_NxJointDesc;
};

struct NxFixedJointDesc {
    NxJointDesc __base_NxJointDesc;
};

struct NxJointLimitDesc {
    NxReal value;
    NxReal restitution;
    NxReal hardness;
};

struct NxJointLimitPairDesc {
    NxJointLimitDesc low;
    NxJointLimitDesc high;
};

struct NxD6JointDesc {
    NxJointDesc __base_NxJointDesc;
    NxD6JointMotion xMotion;
    NxD6JointMotion yMotion;
    NxD6JointMotion zMotion;
    NxD6JointMotion twistMotion;
    NxD6JointMotion swing1Motion;
    NxD6JointMotion swing2Motion;
    NxJointLimitDesc linearLimit;
    NxJointLimitPairDesc twistLimit;
    NxJointLimitDesc swing1Limit;
    NxJointLimitDesc swing2Limit;
    NxJointDriveDesc xDrive;
    NxJointDriveDesc yDrive;
    NxJointDriveDesc zDrive;
    NxJointDriveDesc swingDrive;
    NxJointDriveDesc twistDrive;
    NxJointDriveDesc sphericalDrive;
    unsigned char useSpherical;
    NxVec3 drivePosition;
    NxQuat driveOrientation;
    NxVec3 driveLinearVelocity;
    NxVec3 driveAngularVelocity;
    NxReal projectionDistance;
    NxReal projectionAngle;
    NxJointProjectionMode projectionMode;
};

enum NxMaterialFlag {
    NX_MF_ANISOTROPIC = 1,
    NX_MF_MOVING_SURFACE = 2,
    NX_MF_SPRING_CONTACT = 4,
    NxMaterialFlag__nx_force_32bit = 2147483647
};

enum NxCombineMode {
    NX_CM_AVERAGE = 0,
    NX_CM_MIN = 1,
    NX_CM_MULTIPLY = 2,
    NX_CM_MAX = 3,
    NX_CM_TABLE = 4,
    NX_CM_N_VALUES = 5,
    NX_CM_PAD_32 = 4294967295
};

struct NxMaterial {
    NxReal dynamicFriction;
    NxReal staticFriction;
    NxReal spinFriction;
    NxReal rollFriction;
    NxReal restitution;
    NxReal dynamicFrictionV;
    NxReal staticFrictionV;
    NxVec3 dirOfAnisotropy;
    NxVec3 dirOfMotion;
    NxReal speedOfMotion;
    NxU32 flags;
    NxCombineMode frictionCombineMode;
    NxCombineMode restitutionCombineMode;
    void *programData;
};

struct NxMotorDesc {
    NxReal velTarget;
    NxReal maxForce;
    NX_BOOL freeSpin;
};

struct NxPMap {
    NxU32 dataSize;
    void *data;
};

enum NxParameter {
    NX_PENALTY_FORCE = 0,
    NX_MIN_SEPARATION_FOR_PENALTY = 1,
    NX_DEFAULT_SLEEP_LIN_VEL_SQUARED = 2,
    NX_DEFAULT_SLEEP_ANG_VEL_SQUARED = 3,
    NX_BOUNCE_TRESHOLD = 4,
    NX_DYN_FRICT_SCALING = 5,
    NX_STA_FRICT_SCALING = 6,
    NX_MAX_ANGULAR_VELOCITY = 7,
    NX_MESH_MESH_LEVEL = 8,
    NX_ENABLE_MESH_DEBUG = 9,
    NX_COLL_INFINITY = 10,
    NX_CONTINUOUS_CD = 11,
    NX_MESH_HINT_SPEED = 12,
    NX_VISUALIZATION_SCALE = 13,
    NX_VISUALIZE_WORLD_AXES = 14,
    NX_VISUALIZE_BODY_AXES = 15,
    NX_VISUALIZE_BODY_MASS_AXES = 16,
    NX_VISUALIZE_BODY_LIN_VELOCITY = 17,
    NX_VISUALIZE_BODY_ANG_VELOCITY = 18,
    NX_VISUALIZE_BODY_LIN_MOMENTUM = 19,
    NX_VISUALIZE_BODY_ANG_MOMENTUM = 20,
    NX_VISUALIZE_BODY_LIN_ACCEL = 21,
    NX_VISUALIZE_BODY_ANG_ACCEL = 22,
    NX_VISUALIZE_BODY_LIN_FORCE = 23,
    NX_VISUALIZE_BODY_ANG_FORCE = 24,
    NX_VISUALIZE_BODY_REDUCED = 25,
    NX_VISUALIZE_BODY_JOINT_GROUPS = 26,
    NX_VISUALIZE_BODY_CONTACT_LIST = 27,
    NX_VISUALIZE_BODY_JOINT_LIST = 28,
    NX_VISUALIZE_BODY_DAMPING = 29,
    NX_VISUALIZE_BODY_SLEEP = 30,
    NX_VISUALIZE_JOINT_LOCAL_AXES = 31,
    NX_VISUALIZE_JOINT_WORLD_AXES = 32,
    NX_VISUALIZE_JOINT_LIMITS = 33,
    NX_VISUALIZE_JOINT_ERROR = 34,
    NX_VISUALIZE_JOINT_FORCE = 35,
    NX_VISUALIZE_JOINT_REDUCED = 36,
    NX_VISUALIZE_CONTACT_POINT = 37,
    NX_VISUALIZE_CONTACT_NORMAL = 38,
    NX_VISUALIZE_CONTACT_ERROR = 39,
    NX_VISUALIZE_CONTACT_FORCE = 40,
    NX_VISUALIZE_ACTOR_AXES = 41,
    NX_VISUALIZE_COLLISION_AABBS = 42,
    NX_VISUALIZE_COLLISION_SHAPES = 43,
    NX_VISUALIZE_COLLISION_AXES = 44,
    NX_VISUALIZE_COLLISION_COMPOUNDS = 45,
    NX_VISUALIZE_COLLISION_VNORMALS = 46,
    NX_VISUALIZE_COLLISION_FNORMALS = 47,
    NX_VISUALIZE_COLLISION_SPHERES = 48,
    NX_VISUALIZE_COLLISION_SAP = 49,
    NX_VISUALIZE_COLLISION_STATIC = 50,
    NX_VISUALIZE_COLLISION_DYNAMIC = 51,
    NX_VISUALIZE_COLLISION_FREE = 52,
    NX_VISUALIZE_FLUID_EMITTERS = 53,
    NX_VISUALIZE_FLUID_POSITION = 54,
    NX_VISUALIZE_FLUID_VELOCITY = 55,
    NX_VISUALIZE_FLUID_KERNEL_RADIUS = 56,
    NX_VISUALIZE_FLUID_BOUNDS = 57,
    NX_ADAPTIVE_FORCE = 58,
    NX_PARAMS_NUM_VALUES = 59,
    NxParameter__nx_force_32bit = 2147483647
};

struct NxPhysicsSDK {
    void **__vftable;
};

struct NxPointInPlaneJoint {
    NxJoint __base_NxJoint;
};

struct NxPointInPlaneJointDesc {
    NxJointDesc __base_NxJointDesc;
};

struct NxPointOnLineJoint {
    NxJoint __base_NxJoint;
};

struct NxPointOnLineJointDesc {
    NxJointDesc __base_NxJointDesc;
};

struct NxPrismaticJoint {
    NxJoint __base_NxJoint;
};

struct NxPrismaticJointDesc {
    NxJointDesc __base_NxJointDesc;
};

struct NxPulleyJoint {
    NxJoint __base_NxJoint;
};

enum NxPulleyJointFlag {
    NX_PJF_IS_RIGID = 1,
    NxPulleyJointFlag__nx_force_32bit = 2147483647
};

struct NxPulleyJointDesc {
    NxJointDesc __base_NxJointDesc;
    NxVec3 pulley[2];
    NxReal distance;
    NxReal stiffness;
    NxReal ratio;
    NxU32 flags;
};

struct NxRevoluteJoint {
    NxJoint __base_NxJoint;
};

enum NxRevoluteJointFlag {
    NX_RJF_LIMIT_ENABLED = 1,
    NX_RJF_MOTOR_ENABLED = 2,
    NX_RJF_SPRING_ENABLED = 4,
    NxRevoluteJointFlag__nx_force_32bit = 2147483647
};

struct NxPairFlag {
    void *objects[2];
    NxU32 flags;
};

enum NxStandardFences {
    NX_FENCE_RUN_FINISHED = 0,
    NX_NUM_STANDARD_FENCES = 1,
    NxStandardFences__nx_force_32bit = 2147483647
};

enum NxSimulationStatus {
    NX_RIGID_BODY_FINISHED = 1,
    NxSimulationStatus__nx_force_32bit = 2147483647
};

struct NxScene {
    void **__vftable;
    void *userData;
};

enum NxBroadPhaseType {
    NX_BROADPHASE_QUADRATIC = 0,
    NX_BROADPHASE_FULL = 1,
    NX_BROADPHASE_COHERENT = 2,
    NX_BROADPHASE_FORCE_DWORD = 2147483647
};

enum NxTimeStepMethod {
    NX_TIMESTEP_FIXED = 0,
    NX_TIMESTEP_VARIABLE = 1,
    NX_NUM_TIMESTEP_METHODS = 2,
    NxTimeStepMethod__nx_force_32bit = 2147483647
};

struct NxSceneLimits {
    NxU32 maxNbActors;
    NxU32 maxNbBodies;
    NxU32 maxNbStaticShapes;
    NxU32 maxNbDynamicShapes;
    NxU32 maxNbJoints;
};

struct NxSceneDesc {
    NxBroadPhaseType broadPhase;
    NxVec3 gravity;
    NxUserNotify *userNotify;
    NxUserTriggerReport *userTriggerReport;
    NxUserContactReport *userContactReport;
    NxReal maxTimestep;
    NxU32 maxIter;
    NxTimeStepMethod timeStepMethod;
    NxBounds3 *maxBounds;
    NxSceneLimits *limits;
    unsigned char groundPlane;
    unsigned char boundsPlanes;
    unsigned char collisionDetection;
    void *userData;
};

struct NxSceneStats {
    NxI32 numContacts;
    NxI32 maxContacts;
    NxI32 numActors;
    NxI32 numJoints;
    NxI32 numAwake;
    NxI32 numAsleep;
    NxI32 numStaticShapes;
};

enum NxPerformanceFlag {
    NX_PF_LOGCPU = 1,
    NX_PF_LOGCOUNT = 2,
    NX_PF_LOGMEAN = 4,
    NX_PF_ENABLE = 8,
    NxPerformanceFlag__nx_force_32bit = 2147483647
};

struct NxPerformanceInspector {
    void **__vftable;
};

enum NxShapeType {
    NX_SHAPE_PLANE = 0,
    NX_SHAPE_SPHERE = 1,
    NX_SHAPE_BOX = 2,
    NX_SHAPE_CAPSULE = 3,
    NX_SHAPE_MESH = 4,
    NX_SHAPE_COMPOUND = 5,
    NX_SHAPE_COUNT = 6,
    NX_SHAPE_FORCE_DWORD = 2147483647
};

enum NxShapeFlag {
    NX_TRIGGER_ON_ENTER = 1,
    NX_TRIGGER_ON_LEAVE = 2,
    NX_TRIGGER_ON_STAY = 4,
    NX_TRIGGER_ENABLE = 7,
    NX_SF_VISUALIZATION = 8,
    NX_SF_DISABLE_COLLISION = 16,
    NX_SF_FEATURE_INDICES = 32,
    NX_SF_DISABLE_RAYCASTING = 64,
    NX_SF_FLUID_DRAIN = 128,
    NX_SF_FLUID_DRAIN_INVERT = 256,
    NX_SF_FLUID_DISABLE_COLLISION = 512,
    NX_SF_FLUID_ACTOR_REACTION = 1024,
    NxShapeFlag__nx_force_32bit = 2147483647
};

typedef NxShapeFlag NxTriggerFlag;

struct NxShape {
    void **__vftable;
    void *userData;
    void *appData;
};

struct NxBoxShape {
    NxShape __base_NxShape;
};

struct NxCapsuleShape {
    NxShape __base_NxShape;
};

struct NxPlaneShape {
    NxShape __base_NxShape;
};

struct NxSphereShape {
    NxShape __base_NxShape;
};

struct NxSphericalJoint {
    NxJoint __base_NxJoint;
};

enum NxSphericalJointFlag {
    NX_SJF_TWIST_LIMIT_ENABLED = 1,
    NX_SJF_SWING_LIMIT_ENABLED = 2,
    NX_SJF_TWIST_SPRING_ENABLED = 4,
    NX_SJF_SWING_SPRING_ENABLED = 8,
    NX_SJF_JOINT_SPRING_ENABLED = 16,
    NxSphericalJointFlag__nx_force_32bit = 2147483647
};

struct NxSpringAndDamperEffector {
    NxEffector __base_NxEffector;
};

struct NxSpringAndDamperEffectorDesc {
    NxActor *body1;
    NxActor *body2;
    NxVec3 pos1;
    NxVec3 pos2;
    NxReal springDistCompressSaturate;
    NxReal springDistRelaxed;
    NxReal springDistStretchSaturate;
    NxReal springMaxCompressForce;
    NxReal springMaxStretchForce;
    NxReal damperVelCompressSaturate;
    NxReal damperVelStretchSaturate;
    NxReal damperMaxCompressForce;
    NxReal damperMaxStretchForce;
};

struct NxSpringDesc {
    NxReal spring;
    NxReal damper;
    NxReal targetValue;
};

struct NxDistanceJointDesc {
    NxJointDesc __base_NxJointDesc;
    NxReal maxDistance;
    NxReal minDistance;
    NxSpringDesc spring;
    NxU32 flags;
};

struct NxRevoluteJointDesc {
    NxJointDesc __base_NxJointDesc;
    NxJointLimitPairDesc limit;
    NxMotorDesc motor;
    NxSpringDesc spring;
    NxReal projectionDistance;
    NxReal projectionAngle;
    NxU32 flags;
    NxJointProjectionMode projectionMode;
};

struct NxSphericalJointDesc {
    NxJointDesc __base_NxJointDesc;
    NxVec3 swingAxis;
    NxReal projectionDistance;
    NxJointLimitPairDesc twistLimit;
    NxJointLimitDesc swingLimit;
    NxSpringDesc twistSpring;
    NxSpringDesc swingSpring;
    NxSpringDesc jointSpring;
    NxU32 flags;
    NxJointProjectionMode projectionMode;
};

struct NxTriangle {
    NxVec3 verts[3];
};

enum NxHeightFieldAxis {
    NX_X = 0,
    NX_Y = 1,
    NX_Z = 2,
    NX_NOT_HEIGHTFIELD = 255,
    NxHeightFieldAxis__nx_force_32bit = 2147483647
};

struct NxTriangle32 {
    NxU32 v[3];
};

typedef NxU32 NxSubmeshIndex;

enum NxInternalFormat {
    NX_FORMAT_NODATA = 0,
    NX_FORMAT_FLOAT = 1,
    NX_FORMAT_BYTE = 2,
    NX_FORMAT_SHORT = 3,
    NX_FORMAT_INT = 4,
    NxInternalFormat__nx_force_32bit = 2147483647
};

enum NxInternalArray {
    NX_ARRAY_TRIANGLES = 0,
    NX_ARRAY_VERTICES = 1,
    NX_ARRAY_NORMALS = 2,
    NX_ARRAY_HULL_VERTICES = 3,
    NX_ARRAY_HULL_POLYGONS = 4,
    NxInternalArray__nx_force_32bit = 2147483647
};

struct NxTriangleMesh {
    void **__vftable;
};

struct NxTriangleMeshDesc {
    NxSimpleTriangleMesh __base_NxSimpleTriangleMesh;
    NxU32 materialIndexStride;
    void *materialIndices;
    NxHeightFieldAxis heightFieldVerticalAxis;
    NxReal heightFieldVerticalExtent;
    NxPMap *pmap;
    NxReal convexEdgeThreshold;
};

enum NxMeshShapeFlag {
    NX_MESH_SMOOTH_SPHERE_COLLISIONS = 1,
    NxMeshShapeFlag__nx_force_32bit = 2147483647
};

struct NxTriangleMeshShape {
    NxShape __base_NxShape;
};

enum NxContactPairFlag {
    NX_IGNORE_PAIR = 1,
    NX_NOTIFY_ON_START_TOUCH = 2,
    NX_NOTIFY_ON_END_TOUCH = 4,
    NX_NOTIFY_ON_TOUCH = 8,
    NX_NOTIFY_ON_IMPACT = 16,
    NX_NOTIFY_ON_ROLL = 32,
    NX_NOTIFY_ON_SLIDE = 64,
    NxContactPairFlag__nx_force_32bit = 2147483647
};

struct NxContactPair {
    NxActor *actors[2];
    NxConstContactStream stream;
    NxVec3 sumNormalForce;
    NxVec3 sumFrictionForce;
};

struct NxUserContactReport {
    void **__vftable;
};

enum NxFluidContactPairFlag {
    NX_FPF_IGNORE_PAIR = 1,
    NX_FPF_NOTIFY_ON_COLLISION = 2,
    NxFluidContactPairFlag__nx_force_32bit = 2147483647
};

struct NxFluidContactPair {
    NxFluid *fluid;
    NxActor *actor;
    NxConstContactStream stream;
};

struct NxUserFluidContactReport {
    void **__vftable;
};

struct NxUserTriggerReport {
    void **__vftable;
};

struct NxUserNotify {
    void **__vftable;
};

enum NxShapesType {
    NX_STATIC_SHAPES = 1,
    NX_DYNAMIC_SHAPES = 2,
    NX_ALL_SHAPES = 3,
    NxShapesType__nx_force_32bit = 2147483647
};

enum NxRaycastBit {
    NX_RAYCAST_SHAPE = 1,
    NX_RAYCAST_IMPACT = 2,
    NX_RAYCAST_NORMAL = 4,
    NX_RAYCAST_FACE_INDEX = 8,
    NX_RAYCAST_DISTANCE = 16,
    NX_RAYCAST_UV = 32,
    NxRaycastBit__nx_force_32bit = 2147483647
};

struct NxRaycastHit {
    NxShape *shape;
    NxVec3 worldImpact;
    NxVec3 worldNormal;
    NxU32 faceID;
    NxReal distance;
    NxReal u;
    NxReal v;
    NxU32 flags;
};

struct NxUserRaycastReport {
    void **__vftable;
};

typedef NxU16 NxActorGroup;

struct NxActorDescBase {
    NxMat34 globalPose;
    NxBodyDesc *body;
    NxReal density;
    NxU32 flags;
    NxActorGroup group;
    void *userData;
    char *name;
    ActorDescType type;
};

struct NxActorDesc {
    NxActorDescBase __base_NxActorDescBase;
    NxArray_NxShapeDesc_ptr shapes;
};

typedef NxU16 NxCollisionGroup;

typedef NxU16 NxMaterialIndex;

struct NxShapeDesc {
    void **__vftable;
    NxShapeType type;
    NxMat34 localPose;
    NxU32 shapeFlags;
    NxCollisionGroup group;
    NxMaterialIndex materialIndex;
    void *userData;
    char *name;
};

struct NxBoxShapeDesc {
    NxShapeDesc __base_NxShapeDesc;
    NxVec3 dimensions;
};

struct NxCapsuleShapeDesc {
    NxShapeDesc __base_NxShapeDesc;
    NxReal radius;
    NxReal height;
    NxU32 flags;
};

struct NxPlaneShapeDesc {
    NxShapeDesc __base_NxShapeDesc;
    NxVec3 normal;
    NxReal d;
};

struct NxSphereShapeDesc {
    NxShapeDesc __base_NxShapeDesc;
    NxReal radius;
};

struct NxTriangleMeshShapeDesc {
    NxShapeDesc __base_NxShapeDesc;
    NxTriangleMesh *meshData;
    NxU32 meshFlags;
};

typedef NxU16 NxFluidGroup;

struct NxFluid {
    void **__vftable;
    void *userData;
};

enum NxFluidSimulationMethod {
    NX_F_SPH = 1,
    NX_F_NO_PARTICLE_INTERACTION = 2,
    NxFluidSimulationMethod__nx_force_32bit = 2147483647
};

enum NxFluidParticleAction {
    NX_F_TURN_DEAD = 2,
    NX_F_TURN_SIMPLE = 4,
    NxFluidParticleAction__nx_force_32bit = 2147483647
};

enum NxFluidCollisionMethod {
    NX_F_STATIC = 1,
    NX_F_DYNAMIC = 2,
    NX_F_DYNAMIC_ACTOR_REACTION = 4,
    NxFluidCollisionMethod__nx_force_32bit = 2147483647
};

enum NxFluidFlag {
    NX_FF_VISUALIZATION = 1,
    NX_FF_MESH_INCLUDE_SEPARATED = 2,
    NxFluidFlag__nx_force_32bit = 2147483647
};

struct NxFluidEmitter {
    void **__vftable;
    void *userData;
};

enum NxFluidEmitterFlag {
    NX_FEF_VISUALIZATION = 1,
    NX_FEF_BROKEN_ACTOR_REF = 2,
    NX_FEF_FORCE_ON_ACTOR = 4,
    NX_FEF_ADD_ACTOR_VELOCITY = 8,
    NX_FEF_ENABLED = 16,
    NxFluidEmitterFlag__nx_force_32bit = 2147483647
};

enum NxEmitterShape {
    NX_FE_RECTANGULAR = 1,
    NX_FE_ELLIPSE = 2,
    NxEmitterShape__nx_force_32bit = 2147483647
};

enum NxEmitterType {
    NX_FE_CONSTANT_PRESSURE = 1,
    NX_FE_CONSTANT_FLOW_RATE = 2,
    NxEmitterType__nx_force_32bit = 2147483647
};

struct NxFluidEmitterDesc {
    NxMat34 relPose;
    NxActor *frameActor;
    NxU32 type;
    NxU32 maxParticles;
    NxU32 shape;
    NxReal dimensionX;
    NxReal dimensionY;
    NxVec3 randomPos;
    NxReal randomAngle;
    NxReal fluidVelocityMagnitude;
    NxReal rate;
    NxReal particleLifetime;
    NxU32 flags;
    void *userData;
    char *name;
};

struct NxImplicitMesh {
    void **__vftable;
    void *userData;
};

enum NxMeshDataFlags {
    NX_MDF_16_BIT_INDICES = 1,
    NX_MDF_16_BIT_COMPRESSED_FLOATS = 2,
    NX_MDF_INDEXED_MESH = 4,
    NxMeshDataFlags__nx_force_32bit = 2147483647
};

struct NxMeshData {
    void *verticesPosBegin;
    void *verticesNormalBegin;
    NxI32 verticesPosByteStride;
    NxI32 verticesNormalByteStride;
    NxU32 maxVertices;
    NxU32 *numVerticesPtr;
    void *indicesBegin;
    NxI32 indicesByteStride;
    NxU32 maxIndices;
    NxU32 *numTrianglesPtr;
    NxU32 flags;
    char *name;
};

struct NxImplicitMeshDesc {
    NxReal surfaceRadius;
    NxReal singleRadius;
    NxReal blend;
    NxReal triangleSize;
    NxU32 smoothingIterations;
    NxMeshData meshData;
    void *userData;
    char *name;
};

enum NxParticleFlag {
    NX_FP_DIED = 1,
    NX_FP_LIFETIME_EXPIRED = 2,
    NX_FP_DRAINED = 4,
    NX_FP_SEPARATED = 8,
    NxParticleFlag__nx_force_32bit = 2147483647
};

struct NxParticleData {
    NxU32 maxParticles;
    NxU32 *numParticlesPtr;
    NxF32 *bufferPos;
    NxF32 *bufferVel;
    NxF32 *bufferLife;
    NxU32 *bufferFlags;
    NxU32 bufferPosByteStride;
    NxU32 bufferVelByteStride;
    NxU32 bufferLifeByteStride;
    NxU32 bufferFlagsByteStride;
    char *name;
};

struct NxFluidDesc {
    NxArray_NxFluidEmitterDesc emitters;
    NxParticleData initialParticleData;
    NxU32 maxParticles;
    NxReal restParticlesPerMeter;
    NxReal restDensity;
    NxReal kernelRadiusMultiplier;
    NxReal stiffness;
    NxReal viscosity;
    NxReal damping;
    NxReal staticCollisionRestitution;
    NxReal staticCollisionAdhesion;
    NxReal dynamicCollisionRestitution;
    NxReal dynamicCollisionAdhesion;
    NxU32 simulationMethod;
    NxU32 collisionMethod;
    NxU32 onSeparation;
    NxU32 onCollision;
    NxU32 onLifetimeExpired;
    NxImplicitMeshDesc *surfaceMeshDesc;
    NxParticleData particlesWriteData;
    NxU32 flags;
    NxFluidGroup fluidGroup;
    NxCollisionGroup collisionGroup;
    void *userData;
    char *name;
};

unsigned char __cdecl NxBoxContainsPoint(NxBox *box, NxVec3 *p);
void __cdecl NxCreateBox(NxBox *box, NxBounds3 *aabb, NxMat34 *mat);
unsigned char __cdecl NxComputeBoxPlanes(NxBox *box, NxPlane *planes);
unsigned char __cdecl NxComputeBoxPoints(NxBox *box, NxVec3 *pts);
unsigned char __cdecl NxComputeBoxVertexNormals(NxBox *box, NxVec3 *pts);
NxU32 *__cdecl NxGetBoxEdges(void);
NxI32 *__cdecl NxGetBoxEdgesAxes(void);
NxU32 *__cdecl NxGetBoxTriangles(void);
NxVec3 *__cdecl NxGetBoxLocalEdgeNormals(void);
void __cdecl NxComputeBoxWorldEdgeNormal(NxBox *box, NxU32 edge_index, NxVec3 *world_normal);
void __cdecl NxComputeCapsuleAroundBox(NxBox *box, NxCapsule *capsule);
unsigned char __cdecl NxIsBoxAInsideBoxB(NxBox *a, NxBox *b);
NxU32 *__cdecl NxGetBoxQuads(void);
NxU32 *__cdecl NxBoxVertexToQuad(NxU32 vertexIndex);
void __cdecl NxComputeBoxAroundCapsule(NxCapsule *capsule, NxBox *box);
void __cdecl NxSetFPUPrecision24(void);
void __cdecl NxSetFPUPrecision53(void);
void __cdecl NxSetFPUPrecision64(void);
void __cdecl NxSetFPURoundingChop(void);
void __cdecl NxSetFPURoundingUp(void);
void __cdecl NxSetFPURoundingDown(void);
void __cdecl NxSetFPURoundingNear(void);
void __cdecl NxSetFPUExceptions(unsigned char param_0);
int __cdecl NxIntChop(NxF32 *f);
int __cdecl NxIntFloor(NxF32 *f);
int __cdecl NxIntCeil(NxF32 *f);
NxFoundationSDK *__cdecl NxCreateFoundationSDK(NxU32 sdkVersion, NxUserOutputStream *errorStream, NxUserAllocator *allocator);
NxF32 __cdecl NxComputeDistanceSquared(NxRay *ray, NxVec3 *point, NxF32 *t);
NxF32 __cdecl NxComputeSquareDistance(NxSegment *seg, NxVec3 *point, NxF32 *t);
NxBSphereMethod __cdecl NxComputeSphere(NxSphere *sphere, unsigned nb_verts, NxVec3 *verts);
unsigned char __cdecl NxFastComputeSphere(NxSphere *sphere, unsigned nb_verts, NxVec3 *verts);
void __cdecl NxMergeSpheres(NxSphere *merged, NxSphere *sphere0, NxSphere *sphere1);
void __cdecl NxNormalToTangents(NxVec3 *n, NxVec3 *t1, NxVec3 *t2);
unsigned char __cdecl NxDiagonalizeInertiaTensor(NxMat33 *denseInertia, NxVec3 *diagonalInertia, NxMat33 *rotation);
void __cdecl NxFindRotationMatrix(NxVec3 *x, NxVec3 *b, NxMat33 *M);
void __cdecl NxComputeBounds(NxVec3 *min, NxVec3 *max, NxU32 nbVerts, NxVec3 *verts);
NxU32 __cdecl NxCrc32(void *buffer, NxU32 nbBytes);
unsigned char __cdecl NxComputeVolumeIntegrals(NxSimpleTriangleMesh *mesh, NxReal density, NxIntegrals *integrals);
NxF32 __cdecl NxTriangleTriangleDist(NxVec3 *cp0, NxVec3 *cp1, NxVec3 tri0[3], NxVec3 tri1[3]);
NxReal __cdecl NxComputeSphereMass(NxReal radius, NxReal density);
NxReal __cdecl NxComputeSphereDensity(NxReal radius, NxReal mass);
NxReal __cdecl NxComputeBoxMass(NxVec3 *extents, NxReal density);
NxReal __cdecl NxComputeBoxDensity(NxVec3 *extents, NxReal mass);
NxReal __cdecl NxComputeEllipsoidMass(NxVec3 *extents, NxReal density);
NxReal __cdecl NxComputeEllipsoidDensity(NxVec3 *extents, NxReal mass);
NxReal __cdecl NxComputeCylinderMass(NxReal radius, NxReal length, NxReal density);
NxReal __cdecl NxComputeCylinderDensity(NxReal radius, NxReal length, NxReal mass);
NxReal __cdecl NxComputeConeMass(NxReal radius, NxReal length, NxReal density);
NxReal __cdecl NxComputeConeDensity(NxReal radius, NxReal length, NxReal mass);
void __cdecl NxComputeBoxInertiaTensor(NxVec3 *diagInertia, NxReal mass, NxReal xlength, NxReal ylength, NxReal zlength);
void __cdecl NxComputeSphereInertiaTensor(NxVec3 *diagInertia, NxReal mass, NxReal radius, unsigned char hollow);
unsigned char __cdecl NxBoxBoxIntersect(NxVec3 *extents0, NxVec3 *center0, NxMat33 *rotation0, NxVec3 *extents1, NxVec3 *center1, NxMat33 *rotation1, unsigned char fullTest);
NxSepAxis __cdecl NxSeparatingAxis(NxVec3 *extents0, NxVec3 *center0, NxMat33 *rotation0, NxVec3 *extents1, NxVec3 *center1, NxMat33 *rotation1, unsigned char fullTest);
void __cdecl NxSegmentPlaneIntersect(NxVec3 *v1, NxVec3 *v2, NxPlane *plane, NxReal *dist, NxVec3 *pointOnPlane);
unsigned char __cdecl NxRayPlaneIntersect(NxRay *ray, NxPlane *plane, NxReal *dist, NxVec3 *pointOnPlane);
unsigned char __cdecl NxRaySphereIntersect(NxVec3 *origin, NxVec3 *dir, NxVec3 *center, NxReal radius, NxVec3 *coord);
unsigned char __cdecl NxRayTriIntersect(NxVec3 *orig, NxVec3 *dir, NxVec3 *vert0, NxVec3 *vert1, NxVec3 *vert2, float *t, float *u, float *v, unsigned char cull);
unsigned char __cdecl NxSegmentBoxIntersect(NxVec3 *p1, NxVec3 *p2, NxVec3 *bbox_min, NxVec3 *bbox_max, NxVec3 *intercept);
unsigned char __cdecl NxRayAABBIntersect(NxVec3 *min, NxVec3 *max, NxVec3 *origin, NxVec3 *dir, NxVec3 *coord);
NxU32 __cdecl NxRayAABBIntersect2(NxVec3 *min, NxVec3 *max, NxVec3 *origin, NxVec3 *dir, NxVec3 *coord, NxReal *t);
unsigned char __cdecl NxSegmentOBBIntersect(NxVec3 *p0, NxVec3 *p1, NxVec3 *center, NxVec3 *extents, NxMat33 *rot);
unsigned char __cdecl NxSegmentAABBIntersect(NxVec3 *p0, NxVec3 *p1, NxVec3 *min, NxVec3 *max);
unsigned char __cdecl NxRayOBBIntersect(NxRay *ray, NxVec3 *center, NxVec3 *extents, NxMat33 *rot);
NxU32 __cdecl NxRayCapsuleIntersect(NxVec3 *origin, NxVec3 *dir, NxCapsule *capsule, NxReal t[2]);
unsigned char __cdecl NxSweptSpheresIntersect(NxSphere *sphere0, NxVec3 *velocity0, NxSphere *sphere1, NxVec3 *velocity1);
void __cdecl NxJointDesc_SetGlobalAnchor(NxJointDesc *dis, NxVec3 *wsAnchor);
void __cdecl NxJointDesc_SetGlobalAxis(NxJointDesc *dis, NxVec3 *wsAxis);
unsigned char __cdecl NxCreatePMap(NxPMap *pmap, NxTriangleMesh *mesh, NxU32 density, NxUserOutputStream *outputStream);
unsigned char __cdecl NxReleasePMap(NxPMap *pmap);
NxPhysicsSDK *__cdecl NxCreatePhysicsSDK(NxU32 sdkVersion, NxUserAllocator *allocator, NxUserOutputStream *outputStream);
unsigned char __cdecl NxBuildSmoothNormals(NxU32 nbTris, NxU32 nbVerts, NxVec3 *verts, NxU32 *dFaces, NxU16 *wFaces, NxVec3 *normals, unsigned char flip);
