"""Write one reference document per work unit, from committed oracle data.

A bundle is what a writer reconstructing a whole translation unit reads: every row
in address order with its state, prototype, direct edges, indirect-call sites,
referenced strings and decompile, plus the dispatch tables that name the unit's
rows and the unit's dependencies grouped by owning unit. The decompile comes from
the committed Ghidra manifest, else from the pinned supplement, else from Capstone
disassembly, and the bundle says which.

Usage: python unit_bundle.py --work-units work_units.json --inventory inventory.json
           --ghidra oracle/ghidra/manifest.json --capstone oracle/capstone/manifest.json
           --dependencies oracle/dependencies.dot [--supplement oracle/ghidra/supplement.json]
           --unit "core\\RevoluteJoint.cpp" [--unit ...] --output-dir units
"""

import argparse
import bisect
import json
import re
import sys
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parent))

from work_units import load_edges  # noqa: E402


def unit_filename(unit):
    return re.sub(r"[\\/:]+", "__", unit).replace("..", "__to__") + ".md"


class Oracles:
    def __init__(self, inventory, ghidra, capstone, supplement, edges):
        self.rows = {r["id"]: r for r in inventory["functions"]}
        self.by_rva = {int(r["rva"], 16): r["id"] for r in inventory["functions"]}
        self.ghidra = {int(f["rva"], 16): f for f in ghidra["functions"]}
        self.supplement = {int(f["rva"], 16): f for f in (supplement or {}).get("functions", [])}
        self.ins = sorted(capstone["instructions"], key=lambda i: int(i["rva"], 16))
        self.ins_rva = [int(i["rva"], 16) for i in self.ins]
        strings = {int(s["rva"], 16): s["value"] for s in ghidra["strings"]}
        self.refs = sorted((int(r["from_rva"], 16), strings[int(r["to_rva"], 16)])
                           for r in ghidra["references"]
                           if r["to_rva"] and int(r["to_rva"], 16) in strings)
        self.ref_rva = [a for a, _ in self.refs]
        self.callers, self.callees = {}, {}
        for a, b in edges:
            self.callees.setdefault(a, set()).add(b)
            self.callers.setdefault(b, set()).add(a)
        self.dispatch = []
        for obj in inventory.get("data_objects", []):
            try:
                note = json.loads(obj.get("notes") or "")
            except ValueError:
                continue
            if isinstance(note, dict) and isinstance(note.get("targets"), list):
                for slot, target in enumerate(note["targets"]):
                    self.dispatch.append((obj["id"], obj["rva"], slot, int(target, 16)))

    def instructions(self, lo, hi):
        i = bisect.bisect_left(self.ins_rva, lo)
        out = []
        while i < len(self.ins) and self.ins_rva[i] < hi:
            out.append(self.ins[i])
            i += 1
        return out

    def strings(self, lo, hi):
        i = bisect.bisect_left(self.ref_rva, lo)
        out = []
        while i < len(self.refs) and self.ref_rva[i] < hi:
            out.append(self.refs[i])
            i += 1
        return out


def decompile_source(rva, size, oracles):
    function = oracles.ghidra.get(rva)
    if function and function.get("decompiler_status") == "ok" and function.get("decompiler_c"):
        return "ghidra manifest", function["decompiler_c"]
    extra = oracles.supplement.get(rva)
    if extra and extra.get("status") == "ok" and extra.get("decompiler_c"):
        return "ghidra supplement", extra["decompiler_c"]
    lines = [f"{i['rva']}  {i['mnemonic']} {i['operands']}".rstrip()
             for i in oracles.instructions(rva, rva + size)]
    return "capstone disassembly", "\n".join(lines)


def _name(row_id, oracles):
    row = oracles.rows.get(row_id)
    return f"{row_id} ({row['rva']})" if row else row_id


def render_unit(unit, unit_of, oracles):
    ids = sorted(unit["inferred_extent"] + unit["ambiguous_rows"],
                 key=lambda i: int(oracles.rows[i]["rva"], 16))
    own = set(ids)
    out = [f"# {unit['unit']}", "",
           f"Evidenced span: {unit['evidenced_span']}. Rows: {len(ids)} "
           f"({len(unit['ambiguous_rows'])} ambiguous). Generated by tools/unit_bundle.py; "
           f"do not edit by hand.", "", "## Dispatch tables naming this unit's rows", ""]
    rvas = {int(oracles.rows[i]["rva"], 16): i for i in ids}
    tables = [(t, slot, rvas[target]) for t, trva, slot, target in oracles.dispatch
              if target in rvas]
    out += [f"- {t} slot {slot} -> {row}" for t, slot, row in tables] or ["- none"]
    out += ["", "## External dependencies by unit", ""]
    external = {}
    for i in ids:
        for callee in oracles.callees.get(i, ()):
            if callee not in own:
                external.setdefault(unit_of.get(callee, "unassigned"), set()).add(callee)
    out += [f"- {u}: {', '.join(sorted(c))}" for u, c in sorted(external.items())] or ["- none"]
    for i in ids:
        row = oracles.rows[i]
        rva, size = int(row["rva"], 16), row["size"]
        function = oracles.ghidra.get(rva) or oracles.supplement.get(rva) or {}
        label, text = decompile_source(rva, size, oracles)
        indirect = [f"{x['rva']}  {x['mnemonic']} {x['operands']}"
                    for x in oracles.instructions(rva, rva + size) if x["indirect"]]
        strings = [f"{hex(a)}: {s}" for a, s in oracles.strings(rva, rva + size)]
        out += ["", f"## {i} ({row['rva']}, {size} B, {row['state']})", "",
                f"- ambiguous: {'yes' if i in unit['ambiguous_rows'] else 'no'}",
                f"- source: {row.get('source')}",
                f"- implementation: {row.get('implementation')}",
                f"- prototype: {function.get('prototype')}",
                f"- calling convention: {function.get('calling_convention')}, "
                f"stack purge: {function.get('stack_purge')}",
                f"- callers: {', '.join(_name(c, oracles) for c in sorted(oracles.callers.get(i, ()))) or 'none'}",
                f"- callees: {', '.join(_name(c, oracles) for c in sorted(oracles.callees.get(i, ()))) or 'none'}",
                f"- indirect calls: {'; '.join(indirect) or 'none'}",
                f"- strings: {'; '.join(strings) or 'none'}",
                "", f"Decompile ({label}):", "", "```c" if label != "capstone disassembly" else "```asm",
                text, "```"]
    return "\n".join(out) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    for name in ("--work-units", "--inventory", "--ghidra", "--capstone", "--dependencies",
                 "--output-dir"):
        parser.add_argument(name, required=True)
    parser.add_argument("--supplement")
    parser.add_argument("--unit", action="append", required=True)
    args = parser.parse_args(argv)
    try:
        load = lambda p: json.loads(Path(p).read_text(encoding="utf-8"))  # noqa: E731
        units = {u["unit"]: u for u in load(args.work_units)["units"]}
        oracles = Oracles(load(args.inventory), load(args.ghidra), load(args.capstone),
                          load(args.supplement) if args.supplement else None,
                          load_edges(Path(args.dependencies).read_text(encoding="utf-8")))
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    unit_of = {i: name for name, u in units.items()
               for i in u["inferred_extent"] + u["ambiguous_rows"]}
    output = Path(args.output_dir)
    output.mkdir(parents=True, exist_ok=True)
    for name in args.unit:
        if name not in units:
            print(f"error: no unit named {name!r}", file=sys.stderr)
            return 1
        path = output / unit_filename(name)
        path.write_text(render_unit(units[name], unit_of, oracles), encoding="utf-8",
                        newline="\n")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
