# These cases catch host-based selection, invalid overrides, and silent compiler
# fallback. Resolve target assumptions without requiring each native runner.
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(NOT DEFINED TEST_WORK_DIR)
    set(TEST_WORK_DIR "${CMAKE_CURRENT_BINARY_DIR}/backend-selection-tests")
endif()
file(MAKE_DIRECTORY "${TEST_WORK_DIR}")
function(check_backend name system pointer_size override compiler frontend expected)
    set(script "${TEST_WORK_DIR}/${name}.cmake")
    file(WRITE "${script}" "include(\"${repo}/cmake/NxPhysicsBackend.cmake\")\nnovodex_resolve_physics_backend(result \"${system}\" ${pointer_size} ${override} \"${compiler}\" \"${frontend}\")\nmessage(STATUS \"BACKEND_RESULT=\${result}\")\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${script}"
        RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(expected MATCHES "^error:")
        string(SUBSTRING "${expected}" 6 -1 diagnostic)
        if(status EQUAL 0 OR NOT "${stdout}${stderr}" MATCHES "${diagnostic}")
            message(FATAL_ERROR "${name}: expected failure '${diagnostic}'; got ${status}: ${stdout}${stderr}")
        endif()
    elseif(NOT status EQUAL 0 OR NOT stdout MATCHES "BACKEND_RESULT=${expected}([\r\n]|$)")
        message(FATAL_ERROR "${name}: expected backend ${expected}; got ${status}: ${stdout}${stderr}")
    endif()
    message(STATUS "${name}: passed")
endfunction()
check_backend(win32-default Windows 4 OFF MSVC MSVC 1)
check_backend(win32-portable-test Windows 4 ON MSVC MSVC 0)
check_backend(windows64 Windows 8 OFF MSVC MSVC 0)
check_backend(linux64 Linux 8 OFF GNU GNU 0)
check_backend(linux32 Linux 4 OFF GNU GNU 0)
check_backend(macos Darwin 8 OFF AppleClang GNU 0)
check_backend(invalid-windows64 Windows 8 ON MSVC MSVC "error:only valid for Windows 32-bit")
check_backend(invalid-linux Linux 4 ON GNU GNU "error:only valid for Windows 32-bit")
check_backend(unsupported-win32 Windows 4 OFF GNU GNU "error:requires an MSVC-compatible")
check_backend(unsupported-clang-driver Windows 4 OFF Clang GNU "error:requires an MSVC-compatible")
check_backend(clang-cl Windows 4 OFF Clang MSVC 1)
check_backend(portable-gnu-win32 Windows 4 ON GNU GNU 0)
