# Independently configurable actual-source dependency gate; full engine guards
# remain in the parent build. The established overlay wins over upstream.
set(ICE_SOURCE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../../External/opcode")
set(ICE_TREE "${CMAKE_CURRENT_BINARY_DIR}/ice-topology-tree")
file(GLOB_RECURSE ice_upstream_files RELATIVE "${ICE_SOURCE_ROOT}/upstream/Opcode" "${ICE_SOURCE_ROOT}/upstream/Opcode/*")
foreach(rel IN LISTS ice_upstream_files)
    if(EXISTS "${ICE_SOURCE_ROOT}/novodex/${rel}")
        configure_file("${ICE_SOURCE_ROOT}/novodex/${rel}" "${ICE_TREE}/${rel}" COPYONLY)
    else()
        configure_file("${ICE_SOURCE_ROOT}/upstream/Opcode/${rel}" "${ICE_TREE}/${rel}" COPYONLY)
    endif()
endforeach()
file(GLOB_RECURSE ice_overlay_files RELATIVE "${ICE_SOURCE_ROOT}/novodex" "${ICE_SOURCE_ROOT}/novodex/*")
foreach(rel IN LISTS ice_overlay_files)
    configure_file("${ICE_SOURCE_ROOT}/novodex/${rel}" "${ICE_TREE}/${rel}" COPYONLY)
endforeach()
set(ICE_TOPOLOGY_SOURCES IceTopologyTests.cpp SdkAllocatorKernel.cpp FixtureSupport.cpp
    ../../Physics/src/EdgeList.cpp ../../Physics/src/IceAdjacencies.cpp
    "${ICE_TREE}/Ice/IceRevisitedRadix.cpp" "${ICE_TREE}/Ice/IcePlane.cpp"
    "${ICE_TREE}/Ice/IceTriangle.cpp" "${ICE_TREE}/Ice/IceIndexedTriangle.cpp" "${ICE_TREE}/Ice/IceRandom.cpp")
function(nx_ice_topology_target target backend)
    add_executable(${target} ${ICE_TOPOLOGY_SOURCES})
    target_include_directories(${target} PRIVATE . ../../Physics/src/include ../../Physics/include ../../Foundation/include
        ../../Foundation/src/include ../../Foundation/src ${ICE_TREE})
    target_compile_definitions(${target} PRIVATE NX_PHYSICS_USE_X87=${backend} ICE_NO_DLL OPCODE_EXPORTS USE_MINMAX
        WIN32=1 NXP_DLL_EXPORT= NXF_DLL_EXPORT=)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        target_compile_definitions(${target} PRIVATE NX64=1)
    else()
        target_compile_definitions(${target} PRIVATE NX32=1)
    endif()
    target_compile_features(${target} PRIVATE cxx_std_11)
    if(backend)
        target_compile_options(${target} PRIVATE /arch:IA32 /fp:precise /Qfast_transcendentals /FIGeometrySdkHeaderSeam.h)
    else()
        target_compile_options(${target} PRIVATE ${NOVODEX_PORTABLE_FP_OPTIONS})
        if(MSVC)
            target_compile_options(${target} PRIVATE /FIGeometrySdkHeaderSeam.h)
        else()
            target_compile_options(${target} PRIVATE -include GeometrySdkHeaderSeam.h)
        endif()
    endif()
endfunction()
nx_ice_topology_target(NxPortableIceTopologyTests 0)
add_test(NAME Portable.ConvexContact.IceTopology COMMAND NxPortableIceTopologyTests "${CMAKE_CURRENT_SOURCE_DIR}/fixtures/ice-topology-domain-x87.nxpf")
if(WIN32 AND CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" AND CMAKE_SIZEOF_VOID_P EQUAL 4)
    nx_ice_topology_target(NxPortableExportIceTopology 1)
endif()
