// GENERATED by build/make_translation_table.py -- do not edit.
//
// An oracle RVA to the address the rebuilt module put that row at. The two halves come
// from different artifacts: the census records the row and the symbol it was reconstructed
// into, and the candidate's linker map records where that symbol landed. Neither is
// sufficient alone -- the census has no candidate address and the map has no row -- which
// is why 13c could not build this and it can be built now.
//
// Only unambiguous translations are emitted. A row whose symbol matched several candidate
// symbols is left out rather than guessed, because a wrong address is a harness calling the
// wrong function and reporting a result about it.

#pragma once

struct NxRvaTranslation { unsigned oracleRva; unsigned candidateAddress; };

static const NxRvaTranslation kNxRvaTranslations[] = {
	{ 0x0000c170, 0x10004f50u },  // phys_fn_000273  NpPhysicsSDK::setFluidGroupPairFlags
	{ 0x0000c1a0, 0x10004eb0u },  // phys_fn_000275  NpPhysicsSDK::getFluidGroupPairFlags
	{ 0x0000deb0, 0x10005f20u },  // phys_fn_000443  PhysicsSDK::getDebugRenderable
	{ 0x00013070, 0x10007800u },  // phys_fn_000651  NxSceneInternal::initialise
	{ 0x00051040, 0x100052b0u },  // phys_fn_002051  NxReleasePMap
};

static const unsigned kNxRvaTranslationCount =
	sizeof(kNxRvaTranslations) / sizeof(kNxRvaTranslations[0]);
